apiVersion: v1
kind: Pod
metadata:
  annotations:
    scheduling.k8s.io/group-name: tensorflow-dist-mnist-hf9tm-151f26c4-bea6-46b2-ab76-cc86b0a0c2a5
    volcano.sh/job-name: tensorflow-dist-mnist-hf9tm
    volcano.sh/job-retry-count: "0"
    volcano.sh/job-version: "0"
    volcano.sh/queue-name: default
    volcano.sh/task-index: "0"
    volcano.sh/task-spec: worker
    volcano.sh/template-uid: tensorflow-dist-mnist-hf9tm-worker
  creationTimestamp: "2025-10-16T16:39:35Z"
  generation: 1
  labels:
    volcano.sh/job-name: tensorflow-dist-mnist-hf9tm
    volcano.sh/job-namespace: default
    volcano.sh/queue-name: default
    volcano.sh/task-index: "0"
    volcano.sh/task-spec: worker
  name: tensorflow-dist-mnist-hf9tm-worker-0
  namespace: default
  ownerReferences:
  - apiVersion: batch.volcano.sh/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Job
    name: tensorflow-dist-mnist-hf9tm
    uid: 151f26c4-bea6-46b2-ab76-cc86b0a0c2a5
  resourceVersion: "2514129"
  uid: 9e3a406c-95fb-4be5-8b4c-768c7bb8fa9d
spec:
  containers:
  - command:
    - sh
    - -c
    - |
      PS_HOST=`cat /etc/volcano/ps.host | sed 's/$/&:2222/g' | sed 's/^/"/;s/$/"/' | tr "\n" ","`;
      WORKER_HOST=`cat /etc/volcano/worker.host | sed 's/$/&:2222/g' | sed 's/^/"/;s/$/"/' | tr "\n" ","`;
      export TF_CONFIG={\"cluster\":{\"ps\":[${PS_HOST}],\"worker\":[${WORKER_HOST}]},\"task\":{\"type\":\"worker\",\"index\":${VK_TASK_INDEX}},\"environment\":\"cloud\"};
      python /var/tf_dist_mnist/dist_mnist.py
    env:
    - name: VK_TASK_INDEX
      value: "0"
    - name: VC_TASK_INDEX
      value: "0"
    - name: VC_PS_HOSTS
      valueFrom:
        configMapKeyRef:
          key: VC_PS_HOSTS
          name: tensorflow-dist-mnist-hf9tm-svc
    - name: VC_PS_NUM
      valueFrom:
        configMapKeyRef:
          key: VC_PS_NUM
          name: tensorflow-dist-mnist-hf9tm-svc
    - name: VC_WORKER_HOSTS
      valueFrom:
        configMapKeyRef:
          key: VC_WORKER_HOSTS
          name: tensorflow-dist-mnist-hf9tm-svc
    - name: VC_WORKER_NUM
      valueFrom:
        configMapKeyRef:
          key: VC_WORKER_NUM
          name: tensorflow-dist-mnist-hf9tm-svc
    image: volcanosh/dist-mnist-tf-example:0.0.1
    imagePullPolicy: IfNotPresent
    name: tensorflow
    ports:
    - containerPort: 2222
      name: tfjob-port
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/volcano
      name: tensorflow-dist-mnist-hf9tm-svc
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-czcjs
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostname: tensorflow-dist-mnist-hf9tm-worker-0
  nodeName: k8s-nova-3
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Never
  schedulerName: volcano
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  subdomain: tensorflow-dist-mnist-hf9tm
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - configMap:
      defaultMode: 420
      name: tensorflow-dist-mnist-hf9tm-svc
    name: tensorflow-dist-mnist-hf9tm-svc
  - name: kube-api-access-czcjs
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2025-10-16T16:41:36Z"
    observedGeneration: 1
    status: "False"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2025-10-16T16:39:36Z"
    observedGeneration: 1
    reason: PodCompleted
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2025-10-16T16:41:35Z"
    observedGeneration: 1
    reason: PodCompleted
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2025-10-16T16:41:35Z"
    observedGeneration: 1
    reason: PodCompleted
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2025-10-16T16:39:36Z"
    observedGeneration: 1
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://0581a6fc00271134b6578a8e5729202f071f503a4f01692a7c8daa1d69f11cd9
    image: docker.io/volcanosh/dist-mnist-tf-example:0.0.1
    imageID: docker.io/volcanosh/dist-mnist-tf-example@sha256:2a7759c5922ca567eec0ea47ea74aaa48c1b19ab675464f13670dd5214535f03
    lastState: {}
    name: tensorflow
    ready: false
    resources: {}
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: containerd://0581a6fc00271134b6578a8e5729202f071f503a4f01692a7c8daa1d69f11cd9
        exitCode: 0
        finishedAt: "2025-10-16T16:41:35Z"
        reason: Completed
        startedAt: "2025-10-16T16:39:38Z"
    user:
      linux:
        gid: 0
        supplementalGroups:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 6
        - 10
        - 11
        - 20
        - 26
        - 27
        uid: 0
    volumeMounts:
    - mountPath: /etc/volcano
      name: tensorflow-dist-mnist-hf9tm-svc
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-czcjs
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 172.26.132.248
  hostIPs:
  - ip: 172.26.132.248
  observedGeneration: 1
  phase: Succeeded
  podIP: 10.0.2.58
  podIPs:
  - ip: 10.0.2.58
  qosClass: BestEffort
  startTime: "2025-10-16T16:39:36Z"
